CREATE TABLE customer (
id BIGINT GENERATED BY DEFAULT AS IDENTITY(NO CACHE) PRIMARY KEY,
name VARCHAR(100) NOT NULL, 
username VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL
);

CREATE TABLE asset (
id BIGINT GENERATED BY DEFAULT AS IDENTITY(NO CACHE) PRIMARY KEY,
customer_id BIGINT,
asset_name VARCHAR(100) NOT NULL, 
size DOUBLE PRECISION NOT NULL,
usable_size DOUBLE PRECISION NOT NULL
);

INSERT INTO customer (id, name, username, password) VALUES (1, 'Mehmet Ozdemir', 'mehmet', '1234');

-- TRY bakiyesi yüksek olan bir müşteri
INSERT INTO asset (customer_id, asset_name, size, usable_size) VALUES (1, 'TRY', 100000, 100000);
INSERT INTO asset (customer_id, asset_name, size, usable_size) VALUES (1, 'AAPL', 100, 100);
INSERT INTO asset (customer_id, asset_name, size, usable_size) VALUES (1, 'TSLA', 50, 50);
